package frontend;

import backend.AdminRole;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zaki
 */
public class AdminOptions extends javax.swing.JFrame {
    AdminRole admin = new AdminRole();
    /**
     * Creates new form AdminOptions
     */
    public AdminOptions() {
        initComponents();
        this.setVisible (true);
        this.setTitle("Admin Options");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminOptionsLabel = new javax.swing.JLabel();
        addTrainerButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        removeTrainerButton = new javax.swing.JButton();
        viewTrainersButton = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminOptionsLabel.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        adminOptionsLabel.setText("Admin Options");

        addTrainerButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addTrainerButton.setText("Add Trainer");
        addTrainerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTrainerButtonMouseClicked(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        removeTrainerButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        removeTrainerButton.setText("Remove Trainer");
        removeTrainerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeTrainerButtonMouseClicked(evt);
            }
        });

        viewTrainersButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        viewTrainersButton.setText("View Trainers");
        viewTrainersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTrainersButtonMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(adminOptionsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(addTrainerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(removeTrainerButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(viewTrainersButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(logout)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminOptionsLabel)
                .addGap(31, 31, 31)
                .addComponent(addTrainerButton)
                .addGap(18, 18, 18)
                .addComponent(removeTrainerButton)
                .addGap(18, 18, 18)
                .addComponent(viewTrainersButton)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        admin.logout();
        new RoleSelection ();
        this.dispose ();
    }//GEN-LAST:event_logoutMouseClicked

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit (1);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void addTrainerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTrainerButtonMouseClicked
        new AddTrainerPage(admin, this);
        this.dispose();
    }//GEN-LAST:event_addTrainerButtonMouseClicked

    private void removeTrainerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeTrainerButtonMouseClicked
        new RemoveTrainerPage();
        this.dispose();
    }//GEN-LAST:event_removeTrainerButtonMouseClicked

    private void viewTrainersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTrainersButtonMouseClicked
        new ViewTrainersPage();
        this.dispose();
    }//GEN-LAST:event_viewTrainersButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrainerButton;
    private javax.swing.JLabel adminOptionsLabel;
    private javax.swing.JButton logout;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton removeTrainerButton;
    private javax.swing.JButton viewTrainersButton;
    // End of variables declaration//GEN-END:variables
}
