/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

/**
 *
 * @author Zaki
 */
public class TrainerOptions extends javax.swing.JFrame {

    /**
     * Creates new form TrainerOptions
     */
    public TrainerOptions() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Trainer Options");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMemberButton = new javax.swing.JButton();
        viewMembersButton = new javax.swing.JButton();
        addClassesButton = new javax.swing.JButton();
        registerMemberForClassButton = new javax.swing.JButton();
        viewClassesButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        cancelRegistrationButton = new javax.swing.JButton();
        viewRegistrationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMemberButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addMemberButton.setText("Add Member");
        addMemberButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMemberButtonMouseClicked(evt);
            }
        });

        viewMembersButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewMembersButton.setText("View Members");
        viewMembersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMembersButtonMouseClicked(evt);
            }
        });

        addClassesButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addClassesButton.setText("Add Class");
        addClassesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClassesButtonMouseClicked(evt);
            }
        });

        registerMemberForClassButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registerMemberForClassButton.setText("Register Member For Class");
        registerMemberForClassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMemberForClassButtonMouseClicked(evt);
            }
        });

        viewClassesButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewClassesButton.setText("View Classes");
        viewClassesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewClassesButtonMouseClicked(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        cancelRegistrationButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cancelRegistrationButton.setText("Cancel Registration");
        cancelRegistrationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelRegistrationButtonMouseClicked(evt);
            }
        });

        viewRegistrationButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewRegistrationButton.setText("View Registrations");
        viewRegistrationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewRegistrationButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewClassesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewMembersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addClassesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewRegistrationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(registerMemberForClassButton)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addMemberButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewMembersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addClassesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewClassesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerMemberForClassButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelRegistrationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewRegistrationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new RoleSelection();
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void addMemberButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMemberButtonMouseClicked
        new AddMemberPage();
        this.dispose();
    }//GEN-LAST:event_addMemberButtonMouseClicked

    private void viewMembersButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMembersButtonMouseClicked
        new ViewMembersPage();
        this.dispose();
    }//GEN-LAST:event_viewMembersButtonMouseClicked

    private void addClassesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClassesButtonMouseClicked
        new AddClassPage();
        this.dispose();
    }//GEN-LAST:event_addClassesButtonMouseClicked

    private void viewClassesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewClassesButtonMouseClicked
        new ViewClassesPage();
        this.dispose();
    }//GEN-LAST:event_viewClassesButtonMouseClicked

    private void registerMemberForClassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMemberForClassButtonMouseClicked
        new RegisterMemberForClassPage();
        this.dispose();
    }//GEN-LAST:event_registerMemberForClassButtonMouseClicked

    private void cancelRegistrationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelRegistrationButtonMouseClicked
        new CancelRegistrationPage();
        this.dispose();
    }//GEN-LAST:event_cancelRegistrationButtonMouseClicked

    private void viewRegistrationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewRegistrationButtonMouseClicked
        new ViewRegistrationsPage();
        this.dispose();
    }//GEN-LAST:event_viewRegistrationButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassesButton;
    private javax.swing.JButton addMemberButton;
    private javax.swing.JButton cancelRegistrationButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton registerMemberForClassButton;
    private javax.swing.JButton viewClassesButton;
    private javax.swing.JButton viewMembersButton;
    private javax.swing.JButton viewRegistrationButton;
    // End of variables declaration//GEN-END:variables
}
